Update dependencies
rustyscreeps/screeps-starter-rust pull request #19
Opened 2020-10-30 20:35 UTC by DevJac

I've updated the dependencies and added a few `expect()` calls because the `room()` API changed.

2020-11-17 04:37 UTC, ASalvail requested changes
I think I understand what you were going for here, but by removing everything related to the basic script, it completely removes the starting point that was useful for newcomer in rust.

I believe the idea was to imitate the tutorial for screeps in JS, but in a rust format.

Also, I thought that `rand` didn't work with `wasm`!

2020-11-17 04:37 UTC, ASalvail commented on src/main.rs
> +//use screeps::{find, prelude::*, Part, ResourceType, ReturnCode, RoomObjectProperties};
Can you clean that up if it's no longer necessary?

2020-11-17 04:37 UTC, ASalvail commented on src/main.rs
> +//debug!("running spawns");
A lot of dead code.

2020-11-17 16:14 UTC, DevJac commented
Thank you for taking a look.
I thought most of those changes were just personal, I didn't realize they would be affecting this PR.
All I ever intended to have merged was the first commit. I have fixed the PR.

2021-01-01 21:42 UTC, Eadword commented
Can someone approve this PR. Seems like a pretty basic change that is one of the first things I had to fix after getting started myself. I was about to raise a PR only to notice someone had me beat :smile:

2021-01-01 23:21 UTC, ASalvail approved these changes

2021-01-01 23:21 UTC, merged

2021-01-01 23:22 UTC, ASalvail commented
Sorry, I missed that. Thanks for the nudge @Eadword